yatube/posts/urls.py
"""Ссылки для перехода."""

from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_lists')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'))
]

yatube/posts/models.py
"""Модели (таблицы) сайта."""

from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    """Класс групп указывающий поля таблицы."""

    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    """Класс постов указывающий поля таблицы."""

    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )

yatube/posts/views.py
"""Функции отображения страниц."""

from django.shortcuts import render, get_object_or_404
from .models import Post, Group


def index(request):
    """Функция главной страницы."""
    posts = Post.objects.order_by('-pub_date')[:10]
    title = 'Последние обновления на сайте'
    text = 'Последние обновления на сайте'
    context = {
        'title': title,
        'posts': posts,
        'text': text
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Функция страницы группы."""
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    title = f'Записи сообщества {slug}'
    text = f'Страница группы {slug}'
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
        'title': title,
        'text': text
    }
    return render(request, template, context)

yatube/templates/base.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  {% include 'includes/header.html' %}
  <head>    
  <!-- Подключен файл со стандартными стилями бустрап -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <title>
      {% block title %}
      нет контента TITLE
      {% endblock %}
    </title>
  </head>
  <body>
    <div class="container py-2">
    {% block content %}
    нет контента
    {% endblock %}
    </div>
  </body>
{% include 'includes/footer.html' %}
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
  <!-- В дальнейшем тут будет создано полноценное меню -->
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color:red">Ya</span>tube
      </a>
    </div>
  </nav>      
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
<h1>{{ text }}</h1><hr>
{% for post in posts %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
  <li>
    Группа: {{ post.group }}
  </li>
</ul>
<p>{{ post.text }}</p>
{% if post.group %}
<a href= "{% url 'posts:group_lists' post.group.slug %}">
  Все записи группы
</a>
{% endif %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
<h1>{{ text }}</h1><hr>
{% for post in posts %}
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
  <li>
    Группа: {{ post.group }}
  </li>
</ul>
<p>{{ post.text }}</p>
{% if post.group %}
<a href= "{% url 'posts:group_lists' post.group.slug %}">
  все записи группы
</a>
{% endif %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %}